version: "3.5"
services:
  main:
    container_name: mainBot
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgresBot
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=87654321
      - POSTGRES_DB=weatherBot-db
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadminBot
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
